In [12]:
import warnings
warnings.filterwarnings('ignore')

In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/Lead Scoring.csv")
print("Shape:", df.shape)
df.head()

Shape: (9240, 37)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [5]:
df.head()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Prospect ID                                    9240 non-null   str
 1   Lead Number                                    9240 non-null   int64
 2   Lead Origin                                    9240 non-null   str
 3   Lead Source                                    9204 non-null   str
 4   Do Not Email                                   9240 non-null   str
 5   Do Not Call                                    9240 non-null   str
 6   Converted                                      9240 non-null   int64
 7   TotalVisits                                    9103 non-null   float64
 8   Total Time Spent on Website                    9240 non-null   int64
 9   Page Views Per Visit                           9103 non-null   float64
 10  Last Activity                                  9137 non-null   str
 11  Country                                        6779 non-null   str
 12  Specialization                                 7802 non-null   str
 13  How did you hear about X Education             7033 non-null   str
 14  What is your current occupation                6550 non-null   str
 15  What matters most to you in choosing a course  6531 non-null   str
 16  Search                                         9240 non-null   str
 17  Magazine                                       9240 non-null   str
 18  Newspaper Article                              9240 non-null   str
 19  X Education Forums                             9240 non-null   str
 20  Newspaper                                      9240 non-null   str
 21  Digital Advertisement                          9240 non-null   str
 22  Through Recommendations                        9240 non-null   str
 23  Receive More Updates About Our Courses         9240 non-null   str
 24  Tags                                           5887 non-null   str
 25  Lead Quality                                   4473 non-null   str
 26  Update me on Supply Chain Content              9240 non-null   str
 27  Get updates on DM Content                      9240 non-null   str
 28  Lead Profile                                   6531 non-null   str
 29  City                                           7820 non-null   str
 30  Asymmetrique Activity Index                    5022 non-null   str
 31  Asymmetrique Profile Index                     5022 non-null   str
 32  Asymmetrique Activity Score                    5022 non-null   float64
 33  Asymmetrique Profile Score                     5022 non-null   float64
 34  I agree to pay the amount through cheque       9240 non-null   str
 35  A free copy of Mastering The Interview         9240 non-null   str
 36  Last Notable Activity                          9240 non-null   str
dtypes: float64(4), int64(3), str(30)
memory usage: 2.6 MB

In [3]:
missing = df.isnull().sum().sort_values(ascending=False)
missing_percent = (missing / len(df)) * 100

missing_df = pd.DataFrame({"Missing Count": missing, "Missing %": missing_percent})
missing_df[missing_df["Missing Count"] > 0]

                                               Missing Count  Missing %
Lead Quality                                            4767  51.590909
Asymmetrique Profile Index                              4218  45.649351
Asymmetrique Activity Score                             4218  45.649351
Asymmetrique Activity Index                             4218  45.649351
Asymmetrique Profile Score                              4218  45.649351
Tags                                                    3353  36.287879
What matters most to you in choosing a course           2709  29.318182
Lead Profile                                            2709  29.318182
What is your current occupation                         2690  29.112554
Country                                                 2461  26.634199
How did you hear about X Education                      2207  23.885281
Specialization                                          1438  15.562771
City                                                    1420  15.367965
Page Views Per Visit                                     137   1.482684
TotalVisits                                              137   1.482684
Last Activity                                            103   1.114719
Lead Source                                               36   0.389610

In [4]:
df["Converted"].value_counts(normalize=True) * 100

Converted
0    61.461039
1    38.538961
Name: proportion, dtype: float64

In [13]:
# Separate numeric and categorical columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print("🔢 Numeric Columns:", len(numeric_cols))
print(numeric_cols)
print()
print("🔤 Categorical Columns:", len(categorical_cols))
print(categorical_cols)

🔢 Numeric Columns: 7
['Lead Number', 'Converted', 'TotalVisits', 'Total Time Spent on Website', 'Page Views Per Visit', 'Asymmetrique Activity Score', 'Asymmetrique Profile Score']

🔤 Categorical Columns: 30
['Prospect ID', 'Lead Origin', 'Lead Source', 'Do Not Email', 'Do Not Call', 'Last Activity', 'Country', 'Specialization', 'How did you hear about X Education', 'What is your current occupation', 'What matters most to you in choosing a course', 'Search', 'Magazine', 'Newspaper Article', 'X Education Forums', 'Newspaper', 'Digital Advertisement', 'Through Recommendations', 'Receive More Updates About Our Courses', 'Tags', 'Lead Quality', 'Update me on Supply Chain Content', 'Get updates on DM Content', 'Lead Profile', 'City', 'Asymmetrique Activity Index', 'Asymmetrique Profile Index', 'I agree to pay the amount through cheque', 'A free copy of Mastering The Interview', 'Last Notable Activity']

In [7]:
df.describe()

,Lead Number,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score
count,9240.000000,9240.000000,9103.000000,9240.000000,9103.000000,5022.000000,5022.000000
mean,617188.435606,0.385390,3.445238,487.698268,2.362820,14.306252,16.344883
std,23405.995698,0.486714,4.854853,548.021466,2.161418,1.386694,1.811395
min,579533.000000,0.000000,0.000000,0.000000,0.000000,7.000000,11.000000
25%,596484.500000,0.000000,1.000000,12.000000,1.000000,14.000000,15.000000
50%,615479.000000,0.000000,3.000000,248.000000,2.000000,14.000000,16.000000
75%,637387.250000,1.000000,5.000000,936.000000,3.000000,15.000000,18.000000
max,660737.000000,1.000000,251.000000,2272.000000,55.000000,18.000000,20.000000

In [14]:
df.describe(include=['object'])

,Prospect ID,Lead Origin,Lead Source,Do Not Email,Do Not Call,Last Activity,Country,Specialization,How did you hear about X Education,What is your current occupation,...,Lead Quality,Update me on Supply Chain Content,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
count,9240,9240,9204,9240,9240,9137,6779,7802,7033,6550,...,4473,9240,9240,6531,7820,5022,5022,9240,9240,9240
unique,9240,5,21,2,2,17,38,19,10,6,...,5,1,1,6,7,3,3,1,2,16
top,7927b2df-8bba-4d29-b9a2-b6e0beafe620,Landing Page Submission,Google,No,No,Email Opened,India,Select,Select,Unemployed,...,Might be,No,No,Select,Mumbai,02.Medium,02.Medium,No,No,Modified
freq,1,4886,2868,8506,9238,3437,6492,1942,5043,5600,...,1560,9240,9240,4146,3222,3839,2788,9240,6352,3407

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [11]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

Prospect ID: 9240 unique values
Lead Number: 9240 unique values
Lead Origin: 5 unique values
Lead Source: 21 unique values
Do Not Email: 2 unique values
Do Not Call: 2 unique values
Converted: 2 unique values
TotalVisits: 41 unique values
Total Time Spent on Website: 1731 unique values
Page Views Per Visit: 114 unique values
Last Activity: 17 unique values
Country: 38 unique values
Specialization: 19 unique values
How did you hear about X Education: 10 unique values
What is your current occupation: 6 unique values
What matters most to you in choosing a course: 3 unique values
Search: 2 unique values
Magazine: 1 unique values
Newspaper Article: 2 unique values
X Education Forums: 2 unique values
Newspaper: 2 unique values
Digital Advertisement: 2 unique values
Through Recommendations: 2 unique values
Receive More Updates About Our Courses: 1 unique values
Tags: 26 unique values
Lead Quality: 5 unique values
Update me on Supply Chain Content: 1 unique values
Get updates on DM Content: 1 unique values
Lead Profile: 6 unique values
City: 7 unique values
Asymmetrique Activity Index: 3 unique values
Asymmetrique Profile Index: 3 unique values
Asymmetrique Activity Score: 12 unique values
Asymmetrique Profile Score: 10 unique values
I agree to pay the amount through cheque: 1 unique values
A free copy of Mastering The Interview: 2 unique values
Last Notable Activity: 16 unique values